<?php include dirname(__DIR__).'\..\layouts\header.php';?>
<div class="container my-24 px-6 mx-auto">
  <div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
        <div class="overflow-hidden">
            <table class="min-w-full text-center text-sm font-light">
                <thead class="border-b bg-neutral-800 font-large text-white dark:border-neutral-500 dark:bg-neutral-900">
                  <tr>
                    <th class="w-1/6 py-4 ">Username</th>
                    <th class=w-1/6>Task Description</th>
                    <th class=w-1/6>Status</th>
                    <th class=w-1/6>Starter Date</th>
                    <th class=w-1/6>Finished Date</th>
                    <th class=w-1/6>Actions</th>
                  </tr>
                </thead>

                <tbody class="text-center">
                  <?php foreach ($this->allTasks as $task): ?>
                    <tr class="border-b transition duration-300 ease-in-out hover:bg-neutral-200 dark:border-neutral-500 dark:hover:bg-neutral-600">
                      <td class= "py-4">
                        <?php echo $task['username']?></td>
                      <td>
                        <?php echo $task['taskDescription']?></td>
                      <td>
                        <?php echo $task['status']?></td>
                      <td>
                        <?php echo $task['starterDate']?></td>
                      <td>
                        <?php echo $task['finalDate']?></td>
                      <td>

                        <div class="flex justify-center">
                          <div class="flex ">
                            <form action="viewTask" method="POST">
                              <input type="hidden" name="task" value="<?php echo $task['id']?>">
                              <button class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 border border-gray-700 rounded mx-2">View</button>
                            </form>
                          <div class="flex">
                            <form action="editTask" method="POST">
                              <input type="hidden" name="task" value="<?php echo $task['id']?>">
                              <button class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 border border-green-700 rounded mx-2">Edit</button>
                            </form>
                          <div class="flex">
                            <form action="deleteTask" method="POST">
                              <input type="hidden" name="task" value="<?php echo $task['id']?>">
                              <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 border border-red-700 rounded mx-2">Delete</button>
                            </form>
                          </div>
                        </div>
                      </td>
                    </tr>
                    
                  <?php endforeach;?> 
              
                </tbody>

              </table>
            </div>
          </div> 
        </div>
      </div>  
    </div>
  </div> 
</div>

  <form action="addTask" method="POST">
    <input type="hidden" name="task" value="">
    <button class="bg-blue-300">Add Task</button>
  </form>


<?php include dirname(__DIR__).'\..\layouts\footer.php';?>